name: Build and Deploy to gh-pages

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
#     container: docker://ruby:2.7.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6

      - name: Bundle Install
        run: bundle install

      - name: Build
        run: | # TODO: Make baseurl configureable
          mkdir .jekyll-cache build
          bundle exec jekyll build --baseurl="medablog/" -d build

      - name: Deploy
        run: | # TODO: Make target branch configureable
          cd build
          git init
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "jekyll build from Action $GITHUB_SHA"
          git push -f https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git main:gh-pages

on:
  push:
    branches:
      - master  # TODO: Configure source branch
